Sprint2/step2
Flint174/react-burger pull request #4
Opened 2022-11-17 23:16 UTC by Flint174

2022-11-18 04:05 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализована работа с redux
- Реализован DnD

### **Но есть несколько замечаний, которые нужно исправить:**

- Запрос на получение ингредиентов `GET /ingredients` должен происходить в компоненте `App`, а не в BurgerIngredients.

- В компоненте App-header требуется поправить семантику, переделать div-ы в ссылки. А также не нужно его разделять на такие мелкие компоненты, мы точно знаем что там не будет новых ссылок и в хедере слишком мало кода, чтобы его так сильно разделять.

- Перенести верстку из компонента `app-main` в `App`, не нужно создавать компонент только ради 1 обёртки.

- Для всех необходимых для отображения компонента пропсов в propTypes должен задаваться .isRequired. В описании propTypes компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается. Проверьте во всем проекте.

- Компонент `Modal`
  Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

  ```js
  {isOpen && (
      компонент открываемого попапа
  )}
  ```

- Компонент `OrderDetail`, Туда также требуется указывать в описании propTypes `.isRequired`.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **Сделает код лучше:**

- Старайтесь так сильно не разбивать компоненты на более мелкие.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.jsx
>  }
**Надо исправить:** 

Не нужно создавать отдельную переменную ради 1 строчки. Тем более вы её нигде больше не используйте.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    }, [])
**Надо исправить:** 

Запрос должен отправляться в компоненте `App`.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    ]), [])
**Можно лучше:** 

Возможно стоит вынести за пределы компонента, а не использовать useMemo. Иногда чрезмерное использование useMemo может больше навредить оптимизации, чем помочь.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    : acc
**Можно лучше:**

Немного не понимаю зачем тогда 2 проверка, если у нас всё равно возвращается value, почему бы не просто не объединить 2 проверки в 1?

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    }, [tabs])
**Надо исправить:**

Тут не стоит использовать useCallback, т.к tabs у нас константа, и никогда меняться не будет, а также тут нет так много ререндеров, ради которых нужно использовать useCallback. На мемоизацию реакт выделяет дополнительные ресурсы, и иногда это очень плохо может сказаться на производительности приложения.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/bun.jsx
> +export const Bun = ({ type }) => {
**Надо исправить:** 

Вы тут создаете лишние компоненты, у вас приходит type, так почему не сделать 1 компонент, а не создавать множество, используя useMemo (Его тут тоже не стоит использовать, из-за 1 ререндера ничего плохого не случиться).

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/bun.jsx
> +    const alt = 'Выберите булку'
**Надо исправить:**

Не стоит создавать переменную ради 1 строчки текста, если уж создали, тогда делайте её константой. Не забывайте константы пишутся через UPPER_CASE, и их желательно выносить за пределы компонента. Но в вашем случае я бы просто добавил пропс `ingredientType` к `ConstructorElementEmpty` (а также убрал `text`), и через него оперировал текстом.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +        const bunPrice = bun && bun.price ? bun.price * 2 : 0
**Надо исправить:**

Немного не понимаю зачем тут нужно проверка на цену, нам ведь всегда известно что цена у нас будет.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [bun, ingredients])
**Надо исправить:** 

Вот тут как раз-таки лучше использовать useMemo, а не useEffect. useEffect немного нужен для других задач (подписки на события, отправка запросов и т.п).

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [orderNumber])
**Можно лучше:** 

Лучше сразу проверять есть ли `orderNumber` или нет. Не стоит создавать отдельный стейт для этого.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +        dispatch(fetchOrder(JSON.stringify({ ingredients: [bun._id, ...ingredients.map(el => el._id), bun._id] })))
**Можно лучше:** 

`JSON.stringify`, лучше делать в request, не нужно будет каждый раз дублировать это.

А также вынести `[bun._id, ...ingredients.map(el => el._id), bun._id]`, чуть выше в переменную.

```js
    const getOrderDedails = () => {
      const ingredientsIds = [bun._id, ...ingredients.map(el => el._id), bun._id];
      
      dispatch(fetchOrder({ ingredients: ingredientsIds }))
    }
```
Также убрал useCallback, он тоже тут лишний, ререндер будет происходить в любом случае.

В разы легче читается.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/composition-list-item.jsx
> +            <div style={iconStyle}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/composition-list.jsx
> +                    <CompositionListItem uuid={el.uuid} >
**Надо исправить:** 

Перепроверьте пропсы, не вижу что-то там `uuid`.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/composition-list.jsx
> +                    index={index}
~~**Надо исправить:**~~

~~Использовать `index` В качестве `key`, не очень хорошо.~~ ~~https://stackoverflow.com/questions/46735483/error-do-not-use-array-index-in-keys~~

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/composition-list.jsx
> +    const compositionList = useMemo(() =>
**Надо исправить:** 

Тут также лучше сразу в jsx это всё развернуть, а не использовать useMemo. Т.к у вас только 1 зависимость - это `ingredients`.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/composition.jsx
> +            style={style}
**Надо исправить:** 

Кажется css-modules нужно использовать чуток по-другому.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/constructor-element-empty.jsx
> +            : style.empty_element_default
**Можно лучше:**

попробуйте использовать clsx, думаю тут не будет столько проверок, по крайней мере их не будет на виду.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-constructor/constructor-element-empty.jsx
> +    text: PropTypes.string,
**Надо исправить:** этот пропс по ваше логике (нет проверок на undefined) должен быть `isRequired`.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/card.jsx
> +    onClick: PropTypes.func,
**Надо исправить:**

В описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/category.jsx
> +                    : ingredients.filter(el => el._id === info._id).length
**Можно лучше:**

Тут можно оставить только фильтрацию, а проверку на bun сделать в самом компоненте Card.

**Надо исправить:**

Также не забудьте о том, что у нас 2 булки, а не 1.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/category.jsx
> +export const categoryPropTypes = {
**Надо исправить:**

Описаны не все пропсы, которые используются в компоненте.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/ingredient-details/info-field.jsx
>  export const InfoField = ({ name, value }) => {
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается.

Проверьте во всем проекте.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.jsx
> +IngredientDetails.propTypes = ingredientDetailsPropTypes
**Надо исправить:**

Вроде бы уже не используем пропсы.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/utils/types.js
>  }
**Можно лучше:**

Это супер классно, что вы стараетесь выносить propTypes в отдельные файлы, но лучше чтобы они находились рядом с компонентом, за исключением тех случаев когда у вас идёт переиспользование.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/modal-overlay/modal-overlay.jsx
>  export const ModalOverlay = ({ onClose, children }) => {
**Можно лучше:**
Это просто рекомендация. 

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер.

Ниже показана правильная структура компонента `Modal`.

```js
<>
  <div className={styles.modal}> {/** ... */} <div>
  <ModalOverlay onClick={onClose} />
</>

2022-11-18 04:05 UTC, ArslanMustafin commented on src/services/slices/ingredient-details-slice.js
> +            return { ...payload }
**можно лучше:** 

Лучше вернуть просто payload, а не тратить ресурсы на раскрытие.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/services/slices/ingredients-slice.js
> +)
**можно лучше:**
Здесь и далее.

Можно создать отдельную папочку actions, и вынести в отдельные файлики экшены.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/services/slices/order-slice.js
> +    orderNameGenerator('request'),
**Можно лучше:**

кажется вы немного усложняете, лучше просто написать `${name}/request`.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/card.jsx
> +                const newItem = { ...info, uuid: uuidv4() }
**Можно лучше:** 

генерировать uuid лучше в самом экшене, когда вы добавляете ингредмент в конструктор. 

А также нужно использовать кастомный action-creator: https://redux-toolkit.js.org/api/createslice#customizing-generated-action-creators

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/category.jsx
> +    const closeOrderDetails = useCallback(() => {
**Надо исправить:**

При закрытии окна лучше обнулять стейт ингредиента `setDetails(null)`.

2022-11-18 04:05 UTC, ArslanMustafin commented on src/components/burger-ingredients/category.jsx
> +    const closeOrderDetails = useCallback(() => {
**Надо исправить:**

Нужно сменить название, на closeIngredientDetail, а то очень сильно путает.

При закрытии окна лучше обнулять стейт ингредиента `setDetails(null)`.

2022-11-18 14:00 UTC, Flint174 commented on src/components/burger-constructor/composition-list.jsx
> +                    index={index}
он и не используется. Index передается в качестве props

2022-11-18 14:13 UTC, Flint174 commented on src/components/burger-ingredients/card.jsx
> +    onClick: PropTypes.func,
не все пропсы обязательны для компонента... зачем все делать isRequired?

2022-11-19 02:40 UTC, ArslanDev666 commented on src/components/burger-ingredients/card.jsx
> +    onClick: PropTypes.func,
Верно, но вроде бы у карточки  `onClick` точно должен быть обязательным))

2022-11-19 02:46 UTC, ArslanDev666 commented on src/components/burger-constructor/composition-list.jsx
> +                    index={index}
Действительно нету, видимо уже на автомате отметил)) ну окей, вы в таком случае полностью правы🔥.

2022-11-19 04:24 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

### **Это не самое критическое замечание, но его нужно исправить перед началом следующего задания:**

- В компоненте App-header должна быть активная только первая ссылка, а не все.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-22 17:47 UTC, merged